# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.005
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights:
    patch:
      hsv: ${np.array:[2, 0.5, 0.5]}
      pose_vectors: ${np.ones:3}
      principal_curvatures_log: ${np.ones:2}
  x_percent_threshold: 10
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  gsg: null
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
  hypotheses_updater_args:
    max_nneighbors: 10

learning_module_1:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.005
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights:
    patch:
      hsv: ${np.array:[2, 0.5, 0.5]}
      pose_vectors: ${np.ones:3}
      principal_curvatures_log: ${np.ones:2}
  x_percent_threshold: 10
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  gsg: null
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
  hypotheses_updater_args:
    max_nneighbors: 10

learning_module_2:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.005
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights:
    patch:
      hsv: ${np.array:[2, 0.5, 0.5]}
      pose_vectors: ${np.ones:3}
      principal_curvatures_log: ${np.ones:2}
  x_percent_threshold: 10
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  gsg: null
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
  hypotheses_updater_args:
    max_nneighbors: 10

learning_module_3:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.005
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights:
    patch:
      hsv: ${np.array:[2, 0.5, 0.5]}
      pose_vectors: ${np.ones:3}
      principal_curvatures_log: ${np.ones:2}
  x_percent_threshold: 10
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  gsg: null
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
  hypotheses_updater_args:
    max_nneighbors: 10

learning_module_4:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.005
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights:
    patch:
      hsv: ${np.array:[2, 0.5, 0.5]}
      pose_vectors: ${np.ones:3}
      principal_curvatures_log: ${np.ones:2}
  x_percent_threshold: 10
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  gsg: null
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
  hypotheses_updater_args:
    max_nneighbors: 10

learning_module_5:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.005
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights:
    patch:
      hsv: ${np.array:[2, 0.5, 0.5]}
      pose_vectors: ${np.ones:3}
      principal_curvatures_log: ${np.ones:2}
  x_percent_threshold: 10
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  gsg: null
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
  hypotheses_updater_args:
    max_nneighbors: 10

learning_module_6:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.005
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights:
    patch:
      hsv: ${np.array:[2, 0.5, 0.5]}
      pose_vectors: ${np.ones:3}
      principal_curvatures_log: ${np.ones:2}
  x_percent_threshold: 10
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  gsg: null
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
  hypotheses_updater_args:
    max_nneighbors: 10

learning_module_7:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.005
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights:
    patch:
      hsv: ${np.array:[2, 0.5, 0.5]}
      pose_vectors: ${np.ones:3}
      principal_curvatures_log: ${np.ones:2}
  x_percent_threshold: 10
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  gsg: null
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
  hypotheses_updater_args:
    max_nneighbors: 10

learning_module_8:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.005
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights:
    patch:
      hsv: ${np.array:[2, 0.5, 0.5]}
      pose_vectors: ${np.ones:3}
      principal_curvatures_log: ${np.ones:2}
  x_percent_threshold: 10
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  gsg: null
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
  hypotheses_updater_args:
    max_nneighbors: 10
